services:
  backend:
    build:
      context: ./backend
    working_dir: /src
    volumes:
      - ./backend:/src
    command: poetry run fastapi dev app/main.py --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000

  chromadb:
    image: chromadb/chroma
    ports:
      - 8000:8000